local LibraryView = Menu:extend {
    -- ...
    -- callback to be called when a chapter is selected
    on_selected_chapter_callback = nil,
}
function LibraryView:fetchAndShow(onChapterSelected)
    -- ...
    UIManager:show(LibraryView:new {
        -- ...
        on_selected_chapter_callback = onChapterSelected,
    })
    -- ...
end
function LibraryView:onPrimaryMenuChoice(item)
    -- ...
    ChapterListing:fetchAndShow(manga, onReturnCallback, true, self.on_selected_chapter_callback)
    -- ...
end